Repository nasa/progpy, pull requests merged in 2025-05, with the labels that each got.

#217 Update prognostics example notebook
  examples/09_Prognostic Example.ipynb
Labels: documentation

#218 Update prog_server notebook
  examples/10_Prognostics Server.ipynb
Labels: documentation

#220 Fix download link for CMAPSS Data
  src/progpy/datasets/nasa_cmapss.py
Labels: bug, components: datasets

#207 Fix BatteryElectrochemEODEOL model
  src/progpy/models/battery_electrochem.py
  tests/test_battery.py
Labels: bug, documentation, tests, components: models

#219 Format notebooks
  examples/05_Data Driven.ipynb
  examples/07_State Estimation.ipynb
  examples/08_Prediction.ipynb
Labels: documentation

#197 Add battery examples to included models notebook
  examples/03_Existing Models.ipynb
Labels: documentation

#226 Remove analysis workflow file
  .github/workflows/release.yml
Labels: tests
