Repository nasa/progpy, pull requests merged in 2025-04, with the labels that each got.

#202 Update parameter estimation notebook
  examples/02_Parameter Estimation.ipynb
Labels: documentation

#210 Updating supported python versions
  pyproject.toml
  sphinx-config/troubleshooting.rst
Labels: documentation

#213 Fixed battery dataset download
  pyproject.toml
  sphinx-config/releases.rst
  src/progpy/__init__.py
  src/progpy/datasets/nasa_battery.py
Labels: bug

#214 Fix battery dataset
  sphinx-config/releases.rst
  src/progpy/datasets/nasa_battery.py
Labels: bug

#209 Update combining models notebook
  examples/06_Combining Models.ipynb
Labels: documentation

#215 Update physics-based prognostic models notebook
  examples/04_New Models.ipynb
Labels: documentation

#211 Updated caching to use functools
  src/progpy/sim_result.py
Labels: components: simulation
